//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC__CRUD_Application1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Empid { get; set; }
        public string Empname { get; set; }
        public Nullable<decimal> Sal { get; set; }
        public string Location { get; set; }
    }
}
